export const ImagePath = {
    logo: require('../assets/Image/logo.png'),
    user: require('../assets/Image/user.png'),
    lock: require('../assets/Image/lock.png'),
    eye_on: require('../assets/Image/eye_on.png'),
    eye_off: require('../assets/Image/eye_off.png'),
    email: require('../assets/Image/email.png'),
    menu: require('../assets/Image/menu.png'),
    calendar: require('../assets/Image/calendar.png'),
    eye: require('../assets/Image/eye.png'),
    dining: require('../assets/Image/dining.png'),
    table: require('../assets/Image/table.png'),
    bill: require('../assets/Image/bill.png'),
    payment_list: require('../assets/Image/payment_list.png'),
    logout:require('../assets/Image/logout.png'),
    edit_profile:require('../assets/Image/edit_profile.png'),
    sports:require('../assets/Image/sports.png'),
    mybooking:require('../assets/Image/mybooking.png'),
    hdfc_logo:require('../assets/Image/hdfc_logo.png'),
    payment_success:require('../assets/Image/payment_success.png'),
    payment_fali:require('../assets/Image/payment_fali.png')
}